"""Native 1C engine-report generator (evidence class NATIVE_ENGINE_REPORT, NON-validating).

Runs a fixed allowlist of standard 1C reports (data composition schema route) on the 818HA reference clone and
exports each result to a private directory OUTSIDE Git, with a sha256 manifest.

Safety contract (GPT-PM plan erp_mcp-integration-candidate-2026-10-07T09-38-59-875Z-8b11b5):
* The only identity is the dedicated read-only reader ERP_MCP_TEST_READER. Its DPAPI CurrentUser secret is loaded from one
  fixed path. There is no user argument, environment variable or config key and no Admin_1C fallback: nothing in this module
  can name another user, and the admin credential files are not referenced here.
* Before any report runs, the reader must prove PASS_WRITE_DENIED on the disposable probe clone (a rolled-back write
  attempt; only a genuine rights refusal counts, any other error is inconclusive and refuses the run). The reference clone
  never receives a write probe. A read-only AccessRight sweep records the reader's remaining write rights (it keeps some on
  service catalogs and registers) and refuses the run if it may write documents, accounting registers, charts of accounts or
  administer the configuration.
* The reference clone row-count fingerprint is taken as the reader, so it covers only the tables the reader may read
  (coverage is recorded). Before the run the metadata fingerprint and every readable table count must equal the reference
  manifest baseline; after the run the readable fingerprint must be identical. A mismatch makes the outputs void.
* The 1C object model is reached only through the chokepoints ``_get`` / ``_put`` / ``_call`` / ``_new``: a fixed set of
  operation names and COM types. Report names come only from ``ALLOWED_REPORTS``. No generic method invocation exists.
* A report that errors or is empty is recorded as UNAVAILABLE/EMPTY. There is no retry and no elevation.
* NATIVE_ENGINE_REPORT is machine-generated by the same 1C engine a human would use, but no human compared it with a screen:
  it can never satisfy ``scripts/real1c/evidence.py`` (only NATIVE_UI_REPORT counts) and never validates a profile.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import sys
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from scripts.real1c.com_fingerprint import KINDS, readable_fingerprint
from scripts.real1c.manifest import ManifestGateError, verify_reference_manifest

EVIDENCE_CLASS = "NATIVE_ENGINE_REPORT"
READER_USER = "ERP_MCP_TEST_READER"
READER_SECRET = Path("D:/secrets/erp_mcp/test_reader_password.dpapi")
REFERENCE_CLONE = Path("D:/ERP_MCP_Testbed/1c/reference/working/818HA_test_ready")
PROBE_CLONE = Path("D:/ERP_MCP_Testbed/1c/reference/working/818HA_negative_write_probe_v2")
REFERENCE_MANIFEST = Path("D:/ERP_MCP_Testbed/1c/reference/scenario_pack/manifests/REAL1C_REFERENCE_MANIFEST.json")
PRIVATE_ROOT = Path("D:/ERP_MCP_Testbed/real1c_e2e/private_evidence/native_engine_reports")
REPO_ROOT = Path(__file__).resolve().parents[2]
# 1C dates are timezone-naive local values by definition of the platform
REFERENCE_PERIOD = (dt.datetime(2026, 8, 1), dt.datetime(2026, 8, 31, 23, 59, 59))  # noqa: DTZ001


class GeneratorRefused(Exception):
    """A safety gate refused the run before any report was generated."""


class UnallowedOperation(PermissionError):
    """Something tried an operation outside the fixed allowlist."""


@dataclass(frozen=True)
class ReportSpec:
    name: str
    start_params: tuple[str, ...]
    end_params: tuple[str, ...]
    cases: tuple[str, ...]
    note: str


# Standard reports verified (reader identity, read-only) to produce output through the data composition route.
# Module-driven reports (trial balance, account card, account turnovers) return an empty sheet through an external
# connection because their composition lives in an interactive form: they are NOT listed and are recorded as such.
ALLOWED_REPORTS: dict[str, ReportSpec] = {
    spec.name: spec
    for spec in (
        ReportSpec("ДоходыРасходы", ("НачалоПериода",), ("КонецПериода",), ("NR-03", "NR-04"),
                   "Income and expense by period (cost-allocation view)"),
        ReportSpec("ДоходыИРасходыПоДокументам", ("НачалоПериода",), ("КонецПериода",), ("NR-03", "NR-04"),
                   "Income and expense by document"),
        ReportSpec("ОстаткиДенежныхСредств", (), ("Период",), ("NR-07",), "Cash and bank balances at the end date"),
        ReportSpec("ОстаткиТоваров", (), ("КонецПериода",), ("NR-05", "NR-06"), "Inventory balances at the end date"),
        ReportSpec("ДвижениеТоваров", (), ("КонецПериода",), ("NR-06",), "Inventory movements"),
        ReportSpec("ЗадолженностьПоставщикам", ("НачалоПериода", "НачалоПериодаОстатки"),
                   ("КонецПериода", "КонецПериодаОстатки"), (), "Supplier debt"),
        ReportSpec("ВзаиморасчетыСКонтрагентами", ("НачалоПериода", "НачалоПериодаОстатки"),
                   ("КонецПериода", "КонецПериодаОстатки"), (), "Settlements with counterparties"),
    )
}

# --- the fixed object-model vocabulary (nothing else is reachable) -----------------------------------------------------
_GET = frozenset({"Reports", "DataCompositionSchema", "SettingsComposer", "Settings", "DataParameters", "Items",
                  "DefaultSettings", "Parameter", "TableHeight", "TableWidth", "SpreadsheetDocumentFileType", "XLSX"})
_PUT = frozenset({"Value", "Use"})
_CALL = frozenset({"UserName", "Create", "NewObject", "String", "Initialize", "LoadSettings", "Get", "Count", "Execute",
                   "SetDocument", "Output", "Write"})
_NEW = frozenset({"DataCompositionAvailableSettingsSource", "DataCompositionTemplateComposer", "DataCompositionProcessor",
                  "SpreadsheetDocument", "DataCompositionResultSpreadsheetDocumentOutputProcessor"})


def _get(obj: Any, name: str) -> Any:
    if name not in _GET:
        raise UnallowedOperation(f"get {name!r} is not allowlisted")
    return getattr(obj, name)


def _put(obj: Any, name: str, value: Any) -> None:
    if name not in _PUT:
        raise UnallowedOperation(f"set {name!r} is not allowlisted")
    setattr(obj, name, value)


def _call(obj: Any, name: str, *args: Any) -> Any:
    if name not in _CALL:
        raise UnallowedOperation(f"call {name!r} is not allowlisted")
    return getattr(obj, name)(*args)


def _new(conn: Any, type_name: str, *args: Any) -> Any:
    if type_name not in _NEW:
        raise UnallowedOperation(f"new object type {type_name!r} is not allowlisted")
    return _call(conn, "NewObject", type_name, *args)


def _spec(name: str) -> ReportSpec:
    try:
        return ALLOWED_REPORTS[name]
    except KeyError:
        raise UnallowedOperation(f"report {name!r} is not in the allowlist") from None


# --- connection (reader only) -----------------------------------------------------------------------------------------
@dataclass
class ReaderSession:
    conn: Any
    base: Path
    user: str


def _reader_password() -> str:
    import win32crypt

    blob = READER_SECRET.read_bytes()
    return win32crypt.CryptUnprotectData(blob, None, None, None, 0)[1].decode("utf-8")


def _com_connector() -> Any:
    import win32com.client

    return win32com.client.Dispatch("V83.COMConnector")


def connect_reader(base: Path | str, *, connector: Callable[[], Any] | None = None) -> ReaderSession:
    """Open the infobase as ERP_MCP_TEST_READER. The base must be the reference or the probe clone."""
    base = Path(base)
    if base.resolve() not in {REFERENCE_CLONE.resolve(), PROBE_CLONE.resolve()}:
        raise GeneratorRefused(f"base {base} is neither the reference clone nor the probe clone")
    _assert_distinct_clones()
    password = _reader_password()
    try:
        conn = (connector or _com_connector)().Connect(f'File="{base}";Usr="{READER_USER}";Pwd="{password}";')
    except Exception as exc:  # noqa: BLE001 - never let a connect error text (it may echo the connection string) escape
        raise GeneratorRefused(f"cannot connect as the reader ({type(exc).__name__})") from None
    who = str(_call(conn, "UserName"))
    if who != READER_USER:
        raise GeneratorRefused(f"connected identity {who!r} is not {READER_USER}")
    return ReaderSession(conn, base.resolve(), who)


def _assert_distinct_clones() -> None:
    """The write probe must never be able to land on the reference clone (for example through a junction)."""
    if PROBE_CLONE.resolve() == REFERENCE_CLONE.resolve():
        raise GeneratorRefused("the probe clone resolves to the reference clone")
    probe_db, ref_db = PROBE_CLONE / "1Cv8.1CD", REFERENCE_CLONE / "1Cv8.1CD"
    if probe_db.exists() and ref_db.exists() and os.path.samefile(probe_db, ref_db):
        raise GeneratorRefused("the probe infobase file is the reference infobase file")


_RIGHTS_ERROR_MARKERS = ("access violation", "insufficient rights", "недостаточно прав", "нарушение прав доступа")
FORBIDDEN_WRITE_KINDS = ("Documents", "AccountingRegisters", "ChartsOfAccounts")
WRITE_RIGHTS = ("Insert", "Update", "Delete")


def reader_write_rights(conn: Any) -> dict:
    """Read-only AccessRight sweep (no write is attempted): which objects the reader may insert, update or delete.

    The reader is NOT write-free in 1C terms (it keeps rights on some service catalogs and registers); the sweep records that
    honestly and the run is refused if the reader may write business ledgers or administer the configuration.
    """
    hits: dict[str, list[str]] = {right: [] for right in WRITE_RIGHTS}
    for kind in KINDS:
        for obj in getattr(conn.Metadata, kind, []):
            for right in WRITE_RIGHTS:
                if conn.AccessRight(right, obj):
                    hits[right].append(f"{kind}.{obj.Name}")
    names = sorted({name for found in hits.values() for name in found})
    return {
        "administration": bool(conn.AccessRight("Administration", conn.Metadata)),
        "counts": {right: len(found) for right, found in hits.items()},
        "by_kind": {kind: sum(1 for n in names if n.startswith(kind + ".")) for kind in KINDS
                    if any(n.startswith(kind + ".") for n in names)},
        "names_sha256": hashlib.sha256("\n".join(names).encode("utf-8")).hexdigest(),
        "forbidden": [n for n in names if n.split(".")[0] in FORBIDDEN_WRITE_KINDS],
    }


def write_denial_preflight(session: ReaderSession) -> str:
    """Rolled-back write attempt on the DISPOSABLE probe clone; the reader must be denied. Never runs on the reference."""
    if session.base != PROBE_CLONE.resolve():
        raise GeneratorRefused("the write probe runs on the disposable probe clone only")
    conn = session.conn
    conn.BeginTransaction()
    try:
        name = next(iter(conn.Metadata.Catalogs)).Name
        try:
            item = getattr(conn.Catalogs, name).CreateItem()
            item.Description = "native-engine-preflight"
            item.Write()
        except Exception as exc:  # noqa: BLE001 - classified below: only a rights refusal proves denial
            text = str(exc).lower()
            if any(marker in text for marker in _RIGHTS_ERROR_MARKERS):
                return "PASS_WRITE_DENIED"
            return "INCONCLUSIVE_NON_RIGHTS_ERROR"
        return "FAIL_WRITE_ALLOWED"
    finally:
        conn.RollbackTransaction()


# --- report generation --------------------------------------------------------------------------------------------------
@dataclass
class Sheet:
    document: Any
    rows: int
    cols: int


def generate(conn: Any, name: str, start: dt.datetime, end: dt.datetime) -> Sheet:
    spec = _spec(name)
    report = _call(getattr(_get(conn, "Reports"), spec.name), "Create")
    schema = _get(report, "DataCompositionSchema")
    composer = _get(report, "SettingsComposer")
    _call(composer, "Initialize", _new(conn, "DataCompositionAvailableSettingsSource", schema))
    _call(composer, "LoadSettings", _get(schema, "DefaultSettings"))
    settings = _get(composer, "Settings")
    items = _get(_get(settings, "DataParameters"), "Items")
    for i in range(_call(items, "Count")):
        item = _call(items, "Get", i)
        pname = str(_call(conn, "String", _get(item, "Parameter")))
        if pname in spec.start_params:
            _put(item, "Value", start)
            _put(item, "Use", True)
        elif pname in spec.end_params:
            _put(item, "Value", end)
            _put(item, "Use", True)
    template = _call(_new(conn, "DataCompositionTemplateComposer"), "Execute", schema, settings, None)
    processor = _new(conn, "DataCompositionProcessor")
    _call(processor, "Initialize", template)
    document = _new(conn, "SpreadsheetDocument")
    output = _new(conn, "DataCompositionResultSpreadsheetDocumentOutputProcessor")
    _call(output, "SetDocument", document)
    _call(output, "Output", processor)
    return Sheet(document, int(_get(document, "TableHeight")), int(_get(document, "TableWidth")))


def export_xlsx(conn: Any, sheet: Sheet, path: Path) -> str:
    """Write the sheet to ``path`` (must be outside the repository) and return its sha256."""
    assert_private(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    assert_private(path)  # again after the directory exists, so a junction created in between is resolved
    _call(sheet.document, "Write", str(path), _get(_get(conn, "SpreadsheetDocumentFileType"), "XLSX"))
    return hashlib.sha256(path.read_bytes()).hexdigest()


def assert_private(path: Path) -> None:
    """Outputs live under the private evidence root, never inside any git checkout of this repository."""
    resolved = path.resolve()
    if resolved == REPO_ROOT or REPO_ROOT in resolved.parents:
        raise GeneratorRefused(f"{path} is inside the repository; native engine outputs stay outside Git")
    root = PRIVATE_ROOT.resolve()
    if resolved != root and root not in resolved.parents:
        raise GeneratorRefused(f"{path} is not under the private evidence root")


# --- the run ------------------------------------------------------------------------------------------------------------
def run(*, out_root: Path = PRIVATE_ROOT, reports: list[str] | None = None,
        period: tuple[dt.datetime, dt.datetime] = REFERENCE_PERIOD, connector: Callable[[], Any] | None = None,
        manifest_path: Path = REFERENCE_MANIFEST, now: Callable[[], dt.datetime] = dt.datetime.now) -> dict:
    assert_private(out_root)
    names = reports if reports is not None else list(ALLOWED_REPORTS)
    for name in names:
        _spec(name)  # reject unknown names before any COM connection
    manifest = verify_reference_manifest(manifest_path)

    probe = connect_reader(PROBE_CLONE, connector=connector)
    verdict = write_denial_preflight(probe)
    if verdict != "PASS_WRITE_DENIED":
        raise GeneratorRefused(f"reader write-denial preflight on the probe clone returned {verdict}")

    ref = connect_reader(REFERENCE_CLONE, connector=connector)
    pre = readable_fingerprint(ref.conn)
    if pre["metadata_fingerprint"] != manifest["metadata_fingerprint"]:
        raise GeneratorRefused("reference metadata fingerprint differs from the manifest")
    baseline = (manifest.get("private") or {}).get("per_table_counts")
    if not isinstance(baseline, dict) or not baseline:
        raise GeneratorRefused("the reference manifest carries no per-table baseline")
    if not pre["per_table"]:
        raise GeneratorRefused("the reader could fingerprint no table; the fingerprint gate would be vacuous")
    changed = sorted(key for key, count in pre["per_table"].items() if baseline.get(key) != count)
    if changed:
        raise GeneratorRefused(f"{len(changed)} readable table(s) differ from the reference manifest baseline")

    rights = reader_write_rights(ref.conn)
    if rights["administration"] or rights["forbidden"]:
        raise GeneratorRefused("the reader may administer the configuration or write documents/accounting registers/charts")

    run_dir = out_root / now().strftime("run_%Y%m%d_%H%M%S")
    results = []
    for name in names:
        spec = _spec(name)
        entry: dict[str, Any] = {"report": name, "cases": list(spec.cases), "evidence_class": EVIDENCE_CLASS}
        try:
            sheet = generate(ref.conn, name, *period)
            if sheet.rows == 0 or sheet.cols == 0:
                entry.update(status="EMPTY", rows=sheet.rows, cols=sheet.cols)
            else:
                entry.update(status="GENERATED", rows=sheet.rows, cols=sheet.cols,
                             sha256=export_xlsx(ref.conn, sheet, run_dir / f"{name}.xlsx"))
        except (UnallowedOperation, GeneratorRefused):
            raise
        except Exception as exc:  # noqa: BLE001 - recorded as unavailable, never retried, never elevated
            entry.update(status="UNAVAILABLE", error_type=type(exc).__name__)
        results.append(entry)

    post = readable_fingerprint(ref.conn)
    drift = (post["content_fingerprint_sha256"] != pre["content_fingerprint_sha256"]
             or post["unreadable_fingerprint"] != pre["unreadable_fingerprint"])
    record = {
        "evidence_class": EVIDENCE_CLASS, "validating": False, "identity": ref.user,
        "period": [period[0].isoformat(), period[1].isoformat()],
        "preflight_probe_clone": verdict,
        "fingerprint_pre": pre["content_fingerprint_sha256"], "fingerprint_post": post["content_fingerprint_sha256"],
        "fingerprint_coverage": {"readable_tables": pre["readable_tables"], "unreadable_tables": pre["unreadable_tables"],
                                 "metadata_objects": pre["metadata_object_count"]},
        "evidence_valid": not drift,
        "evidence_basis": (f"row counts unchanged on {pre['readable_tables']} readable tables "
                           f"({pre['unreadable_tables']} unreadable); in-place edits that keep counts are not detected"),
        "reader_write_rights": {k: rights[k] for k in ("counts", "by_kind", "names_sha256")},
        "reports": results,
    }
    run_dir.mkdir(parents=True, exist_ok=True)
    assert_private(run_dir / "manifest.json")
    (run_dir / "manifest.json").write_text(json.dumps(record, ensure_ascii=False, indent=2), encoding="utf-8")
    if drift:
        raise GeneratorRefused("reference fingerprint changed during the run; outputs are not evidence")
    return record


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--report", action="append", choices=sorted(ALLOWED_REPORTS), help="limit to these reports")
    args = parser.parse_args(argv)
    try:
        record = run(reports=args.report)
    except (GeneratorRefused, ManifestGateError, UnallowedOperation) as exc:
        print(f"REFUSED: {exc}", file=sys.stderr)
        return 2
    for entry in record["reports"]:
        print(f"{entry['report']}: {entry['status']} rows={entry.get('rows')} cols={entry.get('cols')}")
    print(f"identity={record['identity']} evidence_valid={record['evidence_valid']} class={EVIDENCE_CLASS} (non-validating)")
    print(f"reader write rights recorded (not write-free): {record['reader_write_rights']['counts']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
